### ISSUE TITLE
Hi how do i use this?

### ISSUE THREAD

**Issue by jamieduk** [3mmarg97/StegHide#1]
No examples given for hiding and unhiding text please reply with 2 examples.

**Comment by ammardev** [comment]
Actually, this script made for educational reasons only. I forget to mention that the script is made to be linked with this article ( It's in Arabic language but maybe google translate help you ):

https://3alam.pro/3mmarg97/articles/steganography-using-lsb-implementation-in-php

Anyway, To hide a text in an image you can use the class like this:
![image](https://user-images.githubusercontent.com/16087389/46099552-babade80-c1cf-11e8-80a3-7e57843d52b6.png)

The `hideText` method should return a number. This number is important to extract the text from the image later. You can save the number in a database to use it later. Or you can create a PR to save the number in the image as a metadata.

And this is an example to extract the text ( The passed number is the number returned by `hideText` method):
![image](https://user-images.githubusercontent.com/16087389/46099654-07061e80-c1d0-11e8-8bc1-e4e187f457f3.png)
